### ISSUE TITLE
unable to run waterCurrentDiluvio

### ISSUE THREAD

**Issue by elgarbe** [disaster-robotics-proalertas/usv_sim_lsa#11]
I get this error:

```
elgarbe@notebook:~/usv_sim_lsa$ ./waterCurrentDiluvio
('--------------------- Loading yaml file ', 'src/usv_water_current/maps/diluvio.yaml')
refX:  477092.4903
refY:  6675824.0
Abrindo arquivo...
Unable to open File: /home/paravisi/hecrasmaps/t3.p02.hdf
None
Unable to open file (Unable to open file: name = '/home/paravisi/hecrasmaps/t3.p02.hdf', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
```

**Comment by marceloparavisi** [comment]
Hello Elgarbe

The script waterCurrentDiluvio should load data from HECRAS simulations, you can download our HECRAS files from this url:
https://drive.google.com/drive/folders/1CjJbe2wZsUF7bmqYOP_vRPixGPzGU8Gt?usp=sharing

Remember that vehicles can be affected by winds and water currents in 3 different ways:
- none: in this way, your vehicle will ignore the disturbance (wind or water current)
- local: in this way, your vehicle will be disturbed with data from simulations (i.e. the HECRAS data of script "./waterCurrentDiluvio")
- global: in this way, your vehicle will be disturbed with a constant value in all position. Wind values is defined into XML files. The water currents can be defined by a ros topic (named **/gazebo/current**).

To specify how your vehicle will affected by the disturbance, you should change the configuration in xacro files. For boats, just edit the file  **usv_sim/xacro/boat_subdivided4.xacro** (see xml code below). 

`<xacro:property name="windType" value="global" />`
`<xacro:property name="waterType" value="global" />`

In value, you can write **none**, **global** or **local**.

If you need any additional assistance, please contact me.

**Comment by elgarbe** [comment]
ok, I will try it.
do you prefer that I will contact you by email for future assistance? I don't have your email address.
thank

**Comment by marceloparavisi** [comment]
I receive an email with all issues. For any doubt just ask me...

Here, other contributors can help too...

**Comment by elgarbe** [comment]
Marcelo, can I get your email?
I need to ask several question about your work that are not issues. Or maybe you can write to lgarberoglio@gmail.com
