### ISSUE TITLE
roslaunch then errors occur

### ISSUE THREAD

**Issue by DaidaiChen** [disaster-robotics-proalertas/usv_sim_lsa#12]
Following your steps, I finished "Compile the stack". However, when I tried to run a scenario:
`  roslaunch usv_sim airboat_scenario1.launch parse:=true`
The Terminal reports:
================================================================================**REQUIRED process [scene_to_spawner-2] has died!
process has finished cleanly
log file: /home/dai/.ros/log/76c6172c-1d54-11e9-80aa-000c29a4b4cb/scene_to_spawner-2*.log
Initiating shutdown!**
================================================================================

Could you please give me some possible suggestions?

Then I have tested another command line:
  `roslaunch usv_sim airboat_scenario1.launch parse:=false`
More warnings and errors appear:
====================================
Warning [parser.cc:778] XML Element[wind], child of element[link] not defined in SDF. Ignoring[wind]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[INFO] [1548058700.519351, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.526243, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.527118, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.556245, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.686703, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.688895, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ERROR] [1548058700.699066, 0.000000]: Simulation number 1
[ INFO] [1548058700.701692280]: ############### Loading freefloating_fluid plugin
[INFO] [1548058700.707942, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.709012, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1548058700.738366, 0.000000]: Calling service /gazebo/spawn_urdf_model

[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'COLOR' is currently not supported

[INFO] [1548058702.034670, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[Err] [Scene.cc:2927] Light [sun] not found. Use topic ~/factory/light to spawn a new light.
[Wrn] [ColladaLoader.cc:1761] Triangle input semantic: 'COLOR' is currently not supported
[INFO] [1548058702.273541, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[buoy4_spawner-9] process has finished cleanly
log file: /home/dai/.ros/log/1921bd6e-1d55-11e9-80aa-000c29a4b4cb/buoy4_spawner-9*.log
[buoy6_spawner-11] process has finished cleanly
log file: /home/dai/.ros/log/1921bd6e-1d55-11e9-80aa-000c29a4b4cb/buoy6_spawner-11*.log
[INFO] [1548058702.507614, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[INFO] [1548058702.734306, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
Segmentation fault (core dumped)
[gazebo_gui-3] process has died [pid 35467, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient --verbose __name:=gazebo_gui __log:=/home/dai/.ros/log/1921bd6e-1d55-11e9-80aa-000c29a4b4cb/gazebo_gui-3.log].
log file: /home/dai/.ros/log/1921bd6e-1d55-11e9-80aa-000c29a4b4cb/gazebo_gui-3*.log

[Wrn] [msgs.cc:1655] Conversion of sensor type[gpu_ray] not suppported.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/underwater/pose/local/info, deleting message. This warning is printed only once.
====================================
The windows of gazebo came out first and shut down auto.

At the real first time, I have once wait to see a 3D simulated scenario with some buoys in two rows.

By the way,  the following command line was also not work for me.
`  ./install_usv_sim`

**Comment by marceloparavisi** [comment]
Hello

The message of the first command (roslaunch usv_sim airboat_scenario1.launch parse:=true) is not an error. It is just an warning that the parsing ended.

================================================================================REQUIRED process [scene_to_spawner-2] has died!
process has finished cleanly
log file: /home/paravisi/.ros/log/f674c498-20ae-11e9-82e4-2c4d54d3cbe8/scene_to_spawner-2*.log
Initiating shutdown!
================================================================================

Can you verify if there is a hidden folder (named .uwsim) in your home directory? If there isn't, move the folder from usv_sim_lsa to your HOME folder. To do that, just run the following command: 
mv .uwsim ~

Regards,
Marcelo
