### ISSUE TITLE
unable to run simulation 

### ISSUE THREAD

**Issue by kgpnaveen** [disaster-robotics-proalertas/usv_sim_lsa#13]
I installed the files as per the process mentioned but when I am running the catkin_make_isolated --install its getting failed. Non of the sub modules is able to installed. When I tried to run catkin_make isolated --install after removing the files in uwsim_resources it works. 
But when I run the roslaunch usv_sim airboat_scenario1.launch parse:true 
its showing error:

REQUIRED process [scene_to_spawner-2] has died!
process has died [pid 18670, exit code 1, cmd /home/naveen/catkin1_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py /home/naveen/catkin1_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1.launch __name:=scene_to_spawner __log:=/home/naveen/.ros/log/b9521c36-2069-11e9-a161-080027a3cc96/scene_to_spawner-2.log].
log file: /home/naveen/.ros/log/b9521c36-2069-11e9-a161-080027a3cc96/scene_to_spawner-2*.log
Initiating shutdown!

Please suggest what should I do to install the files correctly or How can I run the simulation?

**Comment by kgpnaveen** [comment]
And when I try to follow the process exactly to install the files I got this erroe:

Scanning dependencies of target osg_markers
[ 14%] Building CXX object CMakeFiles/osg_markers.dir/src/marker_base.cpp.o
[ 28%] Building CXX object CMakeFiles/osg_markers.dir/src/shape_marker.cpp.o
In file included from /home/naveen/catkin1_ws/src/usv_sim_lsa/uwsim_resources/visualization_osg/osg_markers/include/osg_markers/shape_marker.h:35:0,
                 from /home/naveen/catkin1_ws/src/usv_sim_lsa/uwsim_resources/visualization_osg/osg_markers/src/shape_marker.cpp:35:
/home/naveen/catkin1_ws/src/usv_sim_lsa/uwsim_resources/visualization_osg/osg_markers/include/osg_markers/marker_base.h:41:20: fatal error: osg/Node: No such file or directory
compilation terminated.
CMakeFiles/osg_markers.dir/build.make:86: recipe for target 'CMakeFiles/osg_markers.dir/src/shape_marker.cpp.o' failed
make[2]: *** [CMakeFiles/osg_markers.dir/src/shape_marker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/naveen/catkin1_ws/src/usv_sim_lsa/uwsim_resources/visualization_osg/osg_markers/src/marker_base.cpp:32:0:
/home/naveen/catkin1_ws/src/usv_sim_lsa/uwsim_resources/visualization_osg/osg_markers/include/osg_markers/marker_base.h:41:20: fatal error: osg/Node: No such file or directory
compilation terminated.
CMakeFiles/osg_markers.dir/build.make:62: recipe for target 'CMakeFiles/osg_markers.dir/src/marker_base.cpp.o' failed
make[2]: *** [CMakeFiles/osg_markers.dir/src/marker_base.cpp.o] Error 1
CMakeFiles/Makefile2:111: recipe for target 'CMakeFiles/osg_markers.dir/all' failed
make[1]: *** [CMakeFiles/osg_markers.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'osg_markers': 
  Command '['make', '-j2', '-l2']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/naveen/catkin1_ws/build_isolated/osg_markers && make -j2 -l2

Command failed, exiting.

**Comment by kgpnaveen** [comment]
I removed old catkin_ws files and followed the entire process again to install it but still facing the same issue.

**Comment by marceloparavisi** [comment]
Hello kgpnaveen

Can you run the following command in your terminal?
sudo apt-get install ros-kinetic-osg-markers

If this error persists, you should install the package openscenegraph:
sudo apt-get install openscenegraph

Regards,
Marcelo

**Comment by kgpnaveen** [comment]
Thanks for your response. Yes after installing osg-markers I am able to install the entire package properly. But still when I am running the roslaunch command its not running the simulation. I am getting this message : REQUIRED process [scene_to_spawner-2] has died!
process has died [pid 18735, exit code 1, cmd /home/naveen/catkin_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py /home/naveen/catkin_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1.launch __name:=scene_to_spawner __log:=/home/naveen/.ros/log/9fe5d52c-2171-11e9-bcbb-080027a3cc96/scene_to_spawner-2.log].
log file: /home/naveen/.ros/log/9fe5d52c-2171-11e9-bcbb-080027a3cc96/scene_to_spawner-2*.log
Initiating shutdown!
================================================================================
[scene_to_spawner-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by kgpnaveen** [comment]
After searching for solutions when i did rosdep update then now its working. 
But it works for me when I use parse: = false.
