### ISSUE TITLE
freefolating_gazebo problem

### ISSUE THREAD

**Issue by brunopinto900** [disaster-robotics-proalertas/usv_sim_lsa#15]
I am a student in Portugal and I am developing an autopilot for a tele-commanded sailboat and I found your simulator.

When I installed the simulator, it is not possible to use freefloating_gazebo, the folder is empty and I can not manually put files.

When I access the folder in github, a "NOT FOUND" window appears.

Thanks any help

best regards

![Screenshot from 2019-03-22 12-24-37](https://user-images.githubusercontent.com/48806267/54822769-8ff0a500-4c9d-11e9-9d31-6876f1a5eedc.png)

**Comment by marceloparavisi** [comment]
Hello 

Last week, we missed a commit error on our submodule. Can you pull again the repository?

I think you should execute again the following commands:
git pull
git submodule update

Regards,
Marcelo

**Comment by brunopinto900** [comment]
Bom dia,

O que recomendou fazer: git pull e submodule update funcionou.

No entanto, existe outra situação.

Coloquei um novo issue no github.

Cumprimentos,

Bruno Pinto.



________________________________
De: marceloparavisi <notifications@github.com>
Enviado: terça-feira, 26 de março de 2019 18:19
Para: disaster-robotics-proalertas/usv_sim_lsa
Cc: brunopinto900; Author
Assunto: Re: [disaster-robotics-proalertas/usv_sim_lsa] freefolating_gazebo problem (#15)


Hello

Last week, we missed a commit error on our submodule. Can you pull again the repository?

I think you should execute again the following commands:
git pull
git submodule update

Regards,
Marcelo

**Comment by marceloparavisi** [comment]
Olá Bruno

Vou fechar esse issue e passamos a conversar por lá.

Atenciosamente,
Marcelo

**Comment by brunopinto900** [comment]
Boa tarde,

Está funcionar correctamente.
Muito obrigado.
________________________________
De: marceloparavisi <notifications@github.com>
Enviado: quarta-feira, 27 de março de 2019 19:06
Para: disaster-robotics-proalertas/usv_sim_lsa
Cc: brunopinto900; Author
Assunto: Re: [disaster-robotics-proalertas/usv_sim_lsa] freefolating_gazebo problem (#15)


Closed #15<https://github.com/disaster-robotics-proalertas/usv_sim_lsa/issues/15>.
