### ISSUE TITLE
I have ros laucn error occur

### ISSUE THREAD

**Issue by GoodayTH** [disaster-robotics-proalertas/usv_sim_lsa#16]
![screen1](https://user-images.githubusercontent.com/21971410/54995621-74bdc680-500a-11e9-8673-a25940e1fa0e.png)

I have this error and I change lanch file below

```xml
<!-- using parser  -->
<!-- <include file="$(find usv_sim)/launch/scenarios_launchs/airboat_scenario1_spawner.launch"/>  -->
```

and another error occur ... 

![screen2](https://user-images.githubusercontent.com/21971410/54995707-b8183500-500a-11e9-97b4-c11d9bcfc941.png)

please somesone help me...

**Comment by marceloparavisi** [comment]
Hello 

Last week, we missed a commit error on our submodule. Can you pull again the repository?

I think you should execute again the following commands:
git pull
git submodule update

Regards,
Marcelo

**Comment by GoodayTH** [comment]
thank you so much

**Comment by GoodayTH** [comment]
![screen](https://user-images.githubusercontent.com/21971410/55063445-549a1000-50bb-11e9-936d-13512f64c533.png)

it work! thank you
