### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by jake3991** [disaster-robotics-proalertas/usv_sim_lsa#17]
I installed the software per the instructions, when I try and run after compiling I get the following error. 

Command: roslaunch usv_sim airboat_scenario1.launch parse:=true

ERROR: cannot launch node of type [freefloating_gazebo/uwsim_scene_to_gazebo_spawner.py]: freefloating_gazebo
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/jake/Desktop/sim/src
ROS path [2]=/opt/ros/kinetic/share

Any thoughts as to what is going wrong?

**Comment by marceloparavisi** [comment]
Hello jake3991

Last week, we missed a commit error on our submodule. Can you pull again the repository?

I think you should execute again the following commands:
git pull
git submodule update

Regards,
Marcelo

**Comment by jake3991** [comment]
Thanks! That worked, however it started a new issue.  First I can only start the system with parse set to false and when it starts up no actions are taken.  It looks like everything is online (gazebo, UWsim, etc.) however nothing is published to any rostopics and I can see no movement in the simulator. Any thoughts?

**Comment by wagnerdgarcia** [comment]
Hello, I did the same, but I had git checkout master-melodic, and when executing the above commands the process was aborted and did not end and I continued with the same error.

**Comment by JoseMartinezLeon** [comment]
> Hello, I did the same, but I had git checkout master-melodic, and when executing the above commands the process was aborted and did not end and I continued with the same error.

Hello, I have the same issue. Where you able to solve it? I get this error code:

ERROR: cannot launch node of type [freefloating_gazebo/uwsim_scene_to_gazebo_spawner.py]: freefloating_gazebo
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/leads/catkin_ws/install_isolated/share
ROS path [2]=/opt/ros/melodic/share
