### ISSUE TITLE
error on "catkin_make_isolated --install"

### ISSUE THREAD

**Issue by brunopinto900** [disaster-robotics-proalertas/usv_sim_lsa#18]
![error_gazebo](https://user-images.githubusercontent.com/48806267/55079895-0114cb80-5095-11e9-9f2d-2f634a3ce4d7.png)

**Comment by marceloparavisi** [comment]
Hello Bruno

Can you delete the folders "build_isolated", "devel_isolated", and "install_isolated"?

After that, try to recompile the project...

Regards,
Marcelo
