### ISSUE TITLE
Error on Startup (can't find airboat_scenario1_spawner.launch)

### ISSUE THREAD

**Issue by GoodayTH** [disaster-robotics-proalertas/usv_sim_lsa#23]
![스크린샷, 2019-05-21 19-50-24](https://user-images.githubusercontent.com/21971410/58090233-be3d2300-7c01-11e9-82a7-c6919ad72042.png)

Error like this ... last Issue(#16 ) I have same Error occur so I do below code 

```s
$ git pull
$ git submodule update
```

but... Error occur again... plz help me..

**Comment by marceloparavisi** [comment]
Hello GoodayTH

The file airboat_scenario1_spawner.launch is generated by running : `roslaunch usv_sim airboat_scenario1.launch parse:=true`

The file will be stored into a subfolder of "./install_isolated". 

Please, run the following command sequence:
`source install_isolated/setup.bash`
`roslaunch usv_sim airboat_scenario1.launch parse:=true`
`roslaunch usv_sim airboat_scenario1.launch parse:=false`

Regards,
Marcelo

**Comment by GoodayTH** [comment]
thank you so much

**Comment by GavinGaoYan** [comment]
when I run:roslaunch usv_sim airboat_scenario1.launch parse:=true
it get :
============================================================================REQUIRED process [scene_to_spawner-1] has died!
process has finished cleanly
log file: /home/gavin/.ros/log/16beaa92-d127-11e9-8b58-c8d3ffb64f93/scene_to_spawner-1*.log
Initiating shutdown!
============================================================================
whats the problem?

**Comment by Vince-vd** [comment]
> # when I run:roslaunch usv_sim airboat_scenario1.launch parse:=true
> it get :
> ============================================================================REQUIRED process [scene_to_spawner-1] has died!
> process has finished cleanly
> log file: /home/gavin/.ros/log/16beaa92-d127-11e9-8b58-c8d3ffb64f93/scene_to_spawner-1*.log
> Initiating shutdown!
> 
> whats the problem?

After playing around with the sim a bit I can tell you I'm pretty sure this behavior is as intended. When you execute `roslaunch usv_sim airboat_scenario1.launch parse:=true` it should finish the way you described it. One that's done, try executing the same command but with parse:=false, like this: `roslaunch usv_sim airboat_scenario1.launch parse:=false`
