### ISSUE TITLE
Failed to process package 'uwsim'

### ISSUE THREAD

**Issue by blackcat-meow** [disaster-robotics-proalertas/usv_sim_lsa#26]
I have met some errors when i executed command "catkin_make_isolated --install", please tell me how to solve it.
![2019-07-02 12-41-47屏幕截图](https://user-images.githubusercontent.com/39158642/60483187-02264c00-9cc7-11e9-93a7-993af025dced.png)

**Comment by marceloparavisi** [comment]
Hello blackcat-meow

Can you check if you have the library libcurl3 installed ( sudo apt search libcurl3).

You can install it by executing the following command: 
`sudo apt-get install libcurl3`

Regards,
Marcelo

**Comment by blackcat-meow** [comment]
Thank you for your advice. But I have already installed libcurl3 before. Is it because of the version of libcurl3?

**Comment by marceloparavisi** [comment]
Hello

I'm not sure about the source of this error, but I hope we can solve it.

The package UWSim depends on resource_retriever, which depends on libcurl. Maybe you have an issue with it.

Please, can you execute the following command: 
`ldd /opt/ros/kinetic/lib/libresource_retriever.so |grep curl`
 
In my system, the output was: 
`libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f0e1fd78000)`

Do you have Anaconda 2 installed in your system? If you have it, please try to remove curl-openssl.

Regards,
Marcelo

**Comment by blackcat-meow** [comment]
Thank you for reminding me. I just deactivated the conda environment, then executed command "catkin_make_isolated --install", and the result is successful.
