### ISSUE TITLE
Sailboat Navigation & Wind Current

### ISSUE THREAD

**Issue by johngroves** [disaster-robotics-proalertas/usv_sim_lsa#27]
Hi,

Thanks for all of your work on this project!

Do you have an example of running the wind current modules, and an example of a sailboat navigation module? When running the scenarios, my sailboat model slowly drifts downwind.

**Comment by Vince-vd** [comment]
I have noticed the same, all the other scenario's seem to work as intended (at first glance), but the sailboat just drifts. @johngroves did you ever find a solution for this?
I've tried increasing the wind speed value in the world xml file, but that did not change anything.

Any help would be greatly appreciated!

**Comment by johngroves** [comment]
Hi @Vince-vd, I haven't been able to resolve but see that you opened a PR, does this fix the issue?

**Comment by Vince-vd** [comment]
> Hi @Vince-vd, I hadn't been able to resolve; thanks for diving into this!

Thanks for getting back to me @johngroves 
It did fix it! The example sailboat scenario's work for me with this change.

**Comment by marceloparavisi** [comment]
Hello

I accepted the pull request. 

Thx
