### ISSUE TITLE
Issue compiling stack

### ISSUE THREAD

**Issue by danielfortunato** [disaster-robotics-proalertas/usv_sim_lsa#42]
Hi, 

`cd ~/catkin_ws/`
`catkin_make_isolated --install`

When I run this on the terminal it gives me the following error

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FFTW3F-3_INCLUDE_DIR
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
   used as include directory in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean
FFTW3F-3_LIBRARY
    linked by target "osgOcean" in directory /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean/src/osgOcean

-- Configuring incomplete, errors occurred!
See also "/home/danielfortunato/catkin_ws/build_isolated/uwsim_osgocean/install/CMakeFiles/CMakeOutput.log".
See also "/home/danielfortunato/catkin_ws/build_isolated/uwsim_osgocean/install/CMakeFiles/CMakeError.log".
<== Failed to process package 'uwsim_osgocean': 
  Command '['/home/danielfortunato/catkin_ws/install_isolated/env.sh', 'cmake', '/home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean', '-DCMAKE_INSTALL_PREFIX=/home/danielfortunato/catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/danielfortunato/catkin_ws/build_isolated/uwsim_osgocean && /home/danielfortunato/catkin_ws/install_isolated/env.sh cmake /home/danielfortunato/catkin_ws/src/usv_sim_lsa/uwsim_resources/uwsim_osgocean -DCMAKE_INSTALL_PREFIX=/home/danielfortunato/catkin_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.

Does anyone can tell me what is the issue here?

Thanks is advance.

**Comment by codymarquardt** [comment]
Have you tried this command before attempting to use cmake?

>> sudo apt-get install libfftw3-dev

**Comment by danielfortunato** [comment]
Hello,
It worked perfectly. Thank you.
