### ISSUE TITLE
port code to ros-melodic

### ISSUE THREAD

**Issue by varunk122** [disaster-robotics-proalertas/usv_sim_lsa#53]
I have tried to port your code for ros-melodic and gazebo-9. I got no error while building the pkg after porting it . Looks like I have done something wrong. I got an error while running the command -

`roslaunch usv_sim airboat_scenario1.launch parse:=true`

================================================================================REQUIRED process [scene_to_spawner-2] has died!
process has died [pid 16436, exit code 1, cmd /home/varun/ros/wave_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py /home/varun/ros/wave_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1.launch __name:=scene_to_spawner __log:=/home/varun/.ros/log/0db8ce2a-d5c5-11ea-9900-1c1bb5ea32e7/scene_to_spawner-2.log].
log file: /home/varun/.ros/log/0db8ce2a-d5c5-11ea-9900-1c1bb5ea32e7/scene_to_spawner-2*.log
Initiating shutdown!
================================================================================
[scene_to_spawner-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit

Please help!

**Comment by Elly0723** [comment]
I met this problem too! Any one could help?
