### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by JTDeve** [disaster-robotics-proalertas/usv_sim_lsa#62]
hello,when i run roslaunch ,i have error like this:
..
fail:xxx/install_isolated/share/usv_sim/meshed/buoy2.obj
calling insert_header_and_write for file xxx/urdf/buoy_uwsim.urdf from buoy.xacro
..
==========
process has finished cleanly
...
==========
[scene_to_spawner-2]killing on exit

**Comment by meneguzzi** [comment]
Definitely not enough detail for anything to be done about it.
