### ISSUE TITLE
roslaunch usv_sim airboat_scenario1.launch parse:=true problem

### ISSUE THREAD

**Issue by sevvalyildz** [disaster-robotics-proalertas/usv_sim_lsa#64]
I ran this commands:
source install_isolated/setup.bash
roslaunch usv_sim airboat_scenario1.launch parse:=true
roslaunch usv_sim airboat_scenario1.launch parse:=false

Gazebo doesn't open when I run these commands . I tried to solve this problem but I couldn't.

sevval@sevval:~/catkin_ws$ roslaunch usv_sim airboat_scenario1.launch parse:=true
... logging to /home/sevval/.ros/log/4dad4b5e-5c16-11ec-851d-9bc291b12b5f/roslaunch-sevval-3855.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sevval:38121/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /
    scene_to_spawner (freefloating_gazebo/uwsim_scene_to_gazebo_spawner.py)

ROS_MASTER_URI=http://localhost:11311

process[scene_to_spawner-1]: started with pid [3870]
Parsing launch file:  /home/sevval/catkin_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1.launch
Argument[ 0 ]:  /home/sevval/catkin_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py
Argument[ 1 ]:  /home/sevval/catkin_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1.launch
Argument[ 2 ]:  __name:=scene_to_spawner
Argument[ 3 ]:  __log:=/home/sevval/.ros/log/4dad4b5e-5c16-11ec-851d-9bc291b12b5f/scene_to_spawner-1.log
uwsim_args:  ['', 'disableShaders)', '--dataPath', '/home/sevval/catkin_ws/install_isolated/share/usv_sim', '--configfile', 'scenes/airboat_scenario1.xml']
----------------- Scene file
----------------- Scene file  /home/sevval/catkin_ws/install_isolated/share/usv_sim/scenes/airboat_scenario1.xml
----------------- datapath  [u'/home/sevval/catkin_ws/install_isolated/share/uwsim/data', '/home/sevval/.uwsim/data', '/home/sevval/catkin_ws/install_isolated/share/usv_sim']
---> vehicle: airboat file: urdf/airboat_uwsim.urdf
gazebo_model_file: /home/sevval/catkin_ws/install_isolated/share/usv_sim/xacro/airboat.xacro
running xacro
Traceback (most recent call last):
  File "/home/sevval/catkin_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py", line 351, in <module>
    vehicle_nodes = process_vehicles(scene_xml.findall('vehicle'), datapath)
  File "/home/sevval/catkin_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py", line 224, in process_vehicles
    uwsim_urdf_xml = subprocess.Popen(['rosrun', 'xacro', 'xacro', '--inorder', gazebo_model_file], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
================================================================================REQUIRED process [scene_to_spawner-1] has died!
process has died [pid 3870, exit code 1, cmd /home/sevval/catkin_ws/install_isolated/share/freefloating_gazebo/scripts/uwsim_scene_to_gazebo_spawner.py /home/sevval/catkin_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1.launch __name:=scene_to_spawner __log:=/home/sevval/.ros/log/4dad4b5e-5c16-11ec-851d-9bc291b12b5f/scene_to_spawner-1.log].
log file: /home/sevval/.ros/log/4dad4b5e-5c16-11ec-851d-9bc291b12b5f/scene_to_spawner-1*.log
Initiating shutdown!
================================================================================
[scene_to_spawner-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

sevval@sevval:~/catkin_ws$ roslaunch usv_sim airboat_scenario1.launch parse:=false
... logging to /home/sevval/.ros/log/4dad4b5e-5c16-11ec-851d-9bc291b12b5f/roslaunch-sevval-3740.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: while processing /home/sevval/catkin_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1_spawner.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/sevval/catkin_ws/install_isolated/share/usv_sim/launch/scenarios_launchs/airboat_scenario1_spawner.launch'
The traceback for the exception was written to the log file

**Comment by daiyongatchalmers** [comment]
I met the same problem on Ubuntu 16.04 with the same version of ROS. something error with the airboat_scenrio1.launch
