### ISSUE TITLE
I faced error usv_water_current/GetSpeed.h: No such file or directory

### ISSUE THREAD

**Issue by JeimeRhee** [disaster-robotics-proalertas/usv_sim_lsa#7]
Hello I'm trying  to build and simulate your usv project...

I already set build environment for building your project. But when building usv_water_current the error occured.

Error message is

"usv_sim_lsa/src/usv_water_current/src/main.cpp:11:40: fatal error: usv_water_current/GetSpeed.h: No Such file or directory"

I'm trying to find GetSpeed.h header file in your project I cannot find...

Can you tell me how to solve that problem?

Thank you

**Comment by marceloparavisi** [comment]
Hello JeimeRhee

I couldn't reproduce your error, but I updated the master branch. So I hope you will not face that error again. 

Please, download again the repository and compile it. Let me know if you have any other error.

Thank you,
Marcelo

**Comment by JeimeRhee** [comment]
Hello Marcelo

I really appreciate your help!

I download again the repository, compilation success

Thank you

JeimeRhee
