### ISSUE TITLE
roslaunch usv_sim airboat_scenario1.launch parse:=true   error

### ISSUE THREAD

**Issue by xinshouxiaojie** [disaster-robotics-proalertas/usv_sim_lsa#74]
![image](https://github.com/user-attachments/assets/025b4f65-23e9-4ded-9a80-0e3e49a0ff15)

error content is not found uwsim

**Comment by amamory** [comment]
The simulator doesnt work w this ROS version. Please follow the instruction or use the docker. Any difference in ros or os version is sufficient to create dependencies issues. In addition, upgrading the version is non trivial.
